---
name: Respond to a Pull Request on Master
on:
  pull_request:
    branches: master
jobs:
  test-docker-build:
    name: Test Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v2
      - name: Prepare Environment
        id: prepare
        env:
          DOCKER_IMAGE: ${{ github.repository }}
          DOCKER_PLATFORMS: linux/amd64,linux/arm/v7
        run: |
          VERSION=edge
          TAGS="--tag ${DOCKER_IMAGE,,}:${VERSION}"
          echo ::set-output name=docker_image::${DOCKER_IMAGE,,}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=buildx_args::--platform ${DOCKER_PLATFORMS} \
            --build-arg VERSION=${VERSION} \
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            --build-arg VCS_REF=${GITHUB_SHA::8} \
            ${TAGS} --file ./Dockerfile ./
      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3
      - name: Docker Layer Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build Images
        run: |
          docker buildx build \
            --output "type=image,push=false" \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            ${{ steps.prepare.outputs.buildx_args }}
